export enum ModelName {
    Account = 'accounts',
    User = 'users',
    Payment = 'payments',
    Invoice = 'invoices',
    Card = 'cards',
    Factory = 'factories',
    Feedback = 'feedbacks',
    FAQ = 'faqs',
    Admin = 'admins',
    Wallet = 'wallets',
    Tx = 'transactions',
    Rate = 'rates',
    Category = 'categories',
    Reward = 'rewards',
    Notification = 'notifications',
    Announcement = 'announcements',
    Platform = 'platforms',
}
